server:
  port: 8080
spring:
  application:
    name: user_manage

  cache:
    type: redis

  activemq:
    broker-url:
  redis:
    password: yangbiao
    port: 6379
    host: localhost
    topic:cahce
  datasource:
    url:jdbc:mysql://127.0.0.1:3306/user_base?characterEncoding=utf8
    username: root
    password: yangbiao
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    properties:
  mail:
    host: smtp.163.com
    username: aaaim000111@163.com
    password: biao101919BIAO./
    default-encoding: utf-8
  eu


